version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStrongP4ss*
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      dockerfile: Direcional.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=sqlserver,1433;Database=DirecionalDb;User Id=sa;Password=myStrongP4ss*;Encrypt=False;TrustServerCertificate=True
      - Jwt__Issuer=Direcional
      - Jwt__Audience=DirecionalAudience
      - Jwt__Key=pQ3w6Yt9B2e5H8k1N4r7U0x3A6z9C2v5M8q1L4t7W0y3R6u9
      - RabbitMQ__Host=rabbitmq
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8080:8080"

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - VITE_PROXY_TARGET=http://api:8080
    command: sh -c "npm ci || npm i && npm run dev -- --host --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - api


