version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      dockerfile: Direcional.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=sqlserver,1433;Database=DirecionalDb;User Id=sa;Password=Your_password123;Encrypt=False;TrustServerCertificate=True
      - Jwt__Issuer=Direcional
      - Jwt__Audience=DirecionalAudience
      - Jwt__Key=super_secret_jwt_signing_key_change_me
      - RabbitMQ__Host=rabbitmq
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8080:8080"


